notifications:
  email: false

language: go

go: "1.10"

env:
  global:
    - MAKEFLAGS="-j"

before_install:
  - sudo ln -nfs /bin/bash /bin/sh
  - make prepare

install:
  - make dep

before_script:
  - sudo cp -v ci_docker_daemon.json /etc/docker/daemon.json
  - sudo killall -v dockerd && sudo rm -f /var/run/docker.pid && sudo dockerd 2>&1 | logger -t dockerd &
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}; fi
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD} registry.hub.docker.com; fi
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then cp ~/.docker/config.json docker.json; else echo '{}' > docker.json; fi
  - sudo docker info
  - if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then git remote set-url --push origin https://${GITHUB_TOKEN}@github.com/ivanilves/lstags.git; fi

script:
  - make build
  - make lint
  - make vet
  - if [[ "${TRAVIS_PULL_REQUEST}" != "false" ]]; then make semantic RANGE=$(scripts/travis_range.sh); fi
  - make stress-test-async CONCURRENT_REQUESTS=256
  - make coverage
  - make blackbox-integration-test
  - make docker-image DOCKER_TAG=release
  - make stress-test-wait TIME=60 MODE=silent

after_script:
  - sudo killall -v dockerd

before_deploy:
  - make release

deploy:
  provider: script
  script: make deploy GITHUB_TOKEN=${GITHUB_TOKEN}
  skip_cleanup: true
  on:
    branch: master

branches:
  only:
    - master
